#!/bin/sh
echo "Setup script for Internet Access - Ezhil Viswanathan"
echo "Setting up the default gateway"
/sbin/route add default gw 192.168.7.1

echo "Setting the time using the US ntp pool"
ntpdate -b -s -u pool.ntp.org
